apiVersion: v1
data:
  harvest.yml: |
    Tools:
    Exporters:
        prometheus1:
            exporter: Prometheus
            port_range: 12990-14000
    Defaults:
        use_insecure_tls: true
        collectors:
          - Zapi
          - ZapiPerf
        exporters:
          - prometheus1
    Pollers:
        {{ .Values.netapp.name }}:
            datacenter: {{ .Values.netapp.datacenter }}
            addr: {{ .Values.netapp.addr }}
            username: {{ .Values.netapp.username }}
            password: {{ .Values.netapp.password }}
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  name: {{ .Values.netapp.name }}-cm
