apiVersion: v1
data:
  harvest.yml: |
    Tools:
    Exporters:
        prometheus:
            exporter: Prometheus
    Defaults:
        use_insecure_tls: true
        collectors:
          - Rest
          - RestPerf
          - Ems
        exporters:
          - prometheus
    Pollers:
        {{ .Values.netapp.name }}:
            datacenter: {{ .Values.netapp.datacenter }}
            addr: {{ .Values.netapp.addr }}
            prom_port: {{ .Values.promPort }}
            username: ${USERNAME}
            password: ${PASSWORD}
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  name: {{ .Values.netapp.name }}-cm
