apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.netapp.name }}-exporter
  labels:
    netapp_name: {{ .Values.netapp.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      netapp_name: {{ .Values.netapp.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        netapp_name: {{ .Values.netapp.name }}
    spec:
      containers:
        - args:
            - --poller
            - {{ .Values.netapp.name }}
            - --promPort
            - "{{ .Values.promPort }}"
            - --config
            - /opt/harvest.yml
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: poller-{{ .Values.netapp.name }}
          ports:
            - containerPort: {{ .Values.promPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/harvest/cert
              name: {{ .Values.netapp.name }}-claim
            - mountPath: /opt/harvest.yml
              name: {{ .Values.netapp.name }}-cm
              subPath: harvest.yml
      restartPolicy: Always
      volumes:
        - name: {{ .Values.netapp.name }}-claim
          persistentVolumeClaim:
            claimName: {{ .Values.netapp.name }}-claim
        - configMap:
            items:
              - key: harvest.yml
                path: harvest.yml
            name: {{ .Values.netapp.name }}-cm
          name: {{ .Values.netapp.name }}-cm
