apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hugo-docs.fullname" . }}
  labels:
    {{- include "hugo-docs.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hugo-docs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hugo-docs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hugo-docs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: git-sync
        secret:
          secretName: git-sync
          defaultMode: 0440
      - name: git-checkout
        emptyDir: {}
      containers:
        - name: git-sync
          image: "{{ .Values.git_sync.image.repository }}:{{ .Values.git_sync.image.tag | default .Chart.AppVersion }}"
          args:
           - "--repo={{ .Values.git_sync.git.repo }}"
           - "--link=site"
           - "--branch={{ .Values.git_sync.git.branch }}"
           - "--depth=1"
           - "--root=/checkout"
           - "--ssh-key-file=/etc/git-secret/ssh"
           - "--ssh-known-hosts-file=/etc/git-secret/known_hosts"
           - "--max-failures=-1"
          securityContext:
            {{- toYaml .Values.git_sync.securityContext | nindent 12 }}
          resources:
            limits:
              cpu: {{ .Values.git_sync.resources.limits.cpu }}
              memory: {{ .Values.git_sync.resources.limits.memory }}
            requests:
              cpu: {{ .Values.git_sync.resources.requests.cpu }}
              memory: {{ .Values.git_sync.resources.requests.memory }}
          volumeMounts:
          - name: git-checkout
            mountPath: /checkout
            readOnly: false
          - name: git-sync
            mountPath: /etc/git-secret
            readOnly: false
        - name: hugo
          image: "{{ .Values.hugo.image.repository }}:{{ .Values.hugo.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hugo.image.pullPolicy }}
          env:
          {{- include "hugo-docs.hugo.envValues" . | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.hugo.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 1
            timeoutSeconds: 10
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 1
            timeoutSeconds: 10
            failureThreshold: 20
          args:
            - sh
            - -c
            - >
              sleep 15;
              cd /checkout;
              /hugo server -s site/ --appendPort=false -e $ENVIRONMENT --bind 0.0.0.0 --baseURL $BASE_URL --buildDrafts
          securityContext:
            {{- toYaml .Values.hugo.securityContext | nindent 12 }}
          volumeMounts:
          - name: git-checkout
            mountPath: /checkout
            readOnly: false
          resources:
            {{- toYaml .Values.hugo.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
