{{- if .Values.oauth.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hugo-docs.fullname" . }}-oauth
  labels:
    {{- include "hugo-docs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.oauth.service.type }}
  ports:
    - port: {{ .Values.oauth.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hugo-docs.oauth.selectorLabels" . | nindent 4 }}
{{- end }}