{{- if and .Values.policy.enabled  .Values.oauth.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hugo-docs.fullname" . }}-proxy
  labels:
    {{- include "hugo-docs.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - {{- .Values.policy.namespace }}
            matchLabels:
              kubernetes.io/metadata.name: {{- .Values.policy.namespace }}
          podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - {{ include "hugo-docs.fullname" . }}-oauth
            matchLabels:
              app.kubernetes.io/name: {{ include "hugo-docs.fullname" . }}-oauth
      ports:
        - port: {{ .Values.hugo.service.port }}
          protocol: TCP
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ include "hugo-docs.fullname" . }}
    matchLabels:
      app.kubernetes.io/name: {{ include "hugo-docs.fullname" . }}
  policyTypes:
    - Ingress
{{- end -}}