apiVersion: v1
kind: Service
metadata:
  name: {{ include "hugo-docs.fullname" . }}
  labels:
    {{- include "hugo-docs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hugo.service.type }}
  ports:
    - port: {{ .Values.hugo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hugo-docs.selectorLabels" . | nindent 4 }}
